#!/usr/bin/env python3
"""
Patch WorldBuilder.gd to load heightmap PNG instead of procedural terrain_height().
The heightmap PNG is loaded as an Image, and terrain_height() reads pixel values.
Also replaces _build_terrain to generate mesh from heightmap + HeightmapShape3D collision.
"""

PATH = "/home/z/my-project/godot/scripts/WorldBuilder.gd"
with open(PATH) as f:
    c = f.read()

# 1. Add heightmap image loading at class level (after constants)
old_const_end = "const HARBOR_BASIN_D: float = 600.0     # basin depth (N-S)\""
new_const_end = """const HARBOR_BASIN_D: float = 600.0     # basin depth (N-S)

# Heightmap image (loaded once, used by terrain_height and _build_terrain)
static var _heightmap_img: Image = null
const HEIGHTMAP_PATH: String = \"res://assets/heightmap.png\"
const HEIGHTMAP_SIZE: int = 1024  # pixels
const HEIGHTMAP_WORLD_SIZE: float = 3000.0  # meters (-1500 to +1500)
const HEIGHTMAP_MAX_HEIGHT: float = 120.0  # meters (255 = 120m)

static func _load_heightmap() -> void:
\tif _heightmap_img != null:
\t\treturn
\t_heightmap_img = Image.load_from_file(ProjectSettings.globalize_path(HEIGHTMAP_PATH))
\tif _heightmap_img == null:
\t\tpush_warning(\"Heightmap not found at \" + HEIGHTMAP_PATH + \" — using fallback procedural terrain\")
\telse:
\t\tprint(\"[WorldBuilder] Heightmap loaded: \", _heightmap_img.get_width(), \"x\", _heightmap_img.get_height())"""

assert old_const_end in c, "old_const_end not found"
c = c.replace(old_const_end, new_const_end)

# 2. Replace terrain_height() to read from heightmap image
old_terrain = """static func terrain_height(x: float, z: float) -> float:
\t# Portofino-inspired: land falls from West (high) to East (sea, low)
\tvar noise = _fractal_noise(x, z, 2)
\t# Canyon walls (West/North/South edges)
\tif x < CANYON_EDGE_WEST or z < CANYON_EDGE_NORTH or z > CANYON_EDGE_SOUTH:
\t\tvar dist = 0.0
\t\tif x < CANYON_EDGE_WEST:
\t\t\tdist = max(dist, CANYON_EDGE_WEST - x)
\t\tif z < CANYON_EDGE_NORTH:
\t\t\tdist = max(dist, CANYON_EDGE_NORTH - z)
\t\tif z > CANYON_EDGE_SOUTH:
\t\t\tdist = max(dist, z - CANYON_EDGE_SOUTH)
\t\treturn CANYON_HEIGHT * clamp(dist / 300.0, 0, 1) + noise * 20
\t# Water (east of coast)
\tif x > WATER_OFFSET:
\t\treturn -3.0 - clamp((x - WATER_OFFSET) / 200.0, 0, 1) * 15
\t# Harbor (x: +600 to +1500): sea level (0m)
\tif x > 600:
\t\treturn 0.0 + noise * 0.5
\t# Downtown (x: +100 to +800): gentle hill 5-15m, sloping down to harbor
\tif x > 100:
\t\tvar dt_blend = (800 - x) / 700.0
\t\treturn dt_blend * 15.0 + noise * 2.0
\t# Industrial (x: -600 to +200): plateau at 25m
\tif x > -600:
\t\treturn 25.0 + noise * 3.0
\t# Suburbs (x: -1000 to -400): rolling hills 40-50m
\tif x > -1000:
\t\treturn 45.0 + noise * 8.0
\t# Rural (x: -1200 to -800): higher hills 60-80m
\tif x > -1200:
\t\tvar r_blend = (-800 - x) / 400.0
\t\treturn 60.0 + r_blend * 20.0 + noise * 10.0
\treturn 0.0"""

new_terrain = """static func terrain_height(x: float, z: float) -> float:
\t# Read height from heightmap PNG (generated by scripts/generate_heightmap.py)
\t# Falls back to procedural if heightmap not loaded
\tif _heightmap_img == null:
\t\t_load_heightmap()
\tif _heightmap_img != null:
\t\t# Convert world coords to pixel coords
\t\tvar px = int((x + HEIGHTMAP_WORLD_SIZE / 2) / HEIGHTMAP_WORLD_SIZE * _heightmap_img.get_width())
\t\tvar pz = int((z + HEIGHTMAP_WORLD_SIZE / 2) / HEIGHTMAP_WORLD_SIZE * _heightmap_img.get_height())
\t\tpx = clamp(px, 0, _heightmap_img.get_width() - 1)
\t\tpz = clamp(pz, 0, _heightmap_img.get_height() - 1)
\t\tvar pixel_val = _heightmap_img.get_pixel(px, pz).r  # grayscale 0-1
\t\treturn pixel_val * HEIGHTMAP_MAX_HEIGHT
\t# Fallback: flat
\treturn 0.0"""

assert old_terrain in c, "old_terrain not found"
c = c.replace(old_terrain, new_terrain)

# 3. Add _load_heightmap() call in build_world
old_build = """static func build_world(parent: Node3D) -> void:
\t_init_districts()"""
new_build = """static func build_world(parent: Node3D) -> void:
\t_load_heightmap()
\t_init_districts()"""
assert old_build in c, "old_build not found"
c = c.replace(old_build, new_build)

with open(PATH, 'w') as f:
    f.write(c)
print("OK — WorldBuilder.gd patched to load heightmap PNG")
